# -*- coding: utf-8 -*-
"""SPR-LAB-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7qBRWguNnW2pE7UXS7-N6WsKyrhyJcj
"""

!pip install SpeechRecognition
!apt-get install -y portaudio19-dev
!pip install pyaudio
!pip install fuzzywuzzy[speedup]

import speech_recognition as sr
from fuzzywuzzy import process

# -----------------------------
# Example Telephone Directory
# -----------------------------
phone_directory = {
    "ARIA": "9876543210",
    "JOHN": "9123456789",
    "JESSICA": "9988776655",
    "MICHAEL": "9001122334",
    "SAM": "8745632109"
}

# ------------------------------------------
# Speech recognition function
# ------------------------------------------
def listen_spelled_name():
    recognizer = sr.Recognizer()

    try:
        with sr.Microphone() as source:
            print("Please spell the name (e.g., A R I A): ")
            audio = recognizer.listen(source)
        text = recognizer.recognize_google(audio)
        print("You said:", text)
        return text.upper()

    except sr.UnknownValueError:
        print("Could not understand audio.")
    except sr.RequestError:
        print("Speech service unavailable.")
    except OSError as e:
        if "No Default Input Device Available" in str(e):
            print("\n--- Microphone not found. Please type the name instead. ---")
            text_input = input("Enter the spelled name (e.g., A R I A): ")
            return text_input.upper()
        else:
            print(f"An OSError occurred: {e}")

    return None

# ------------------------------------------
# Name matching + directory lookup
# ------------------------------------------
def lookup_name(spelled_text):
    # Remove spaces from spelled letters
    cleaned = spelled_text.replace(" ", "")
    print("Interpreted name:", cleaned)

    # Fuzzy match against directory keys
    best_match, confidence = process.extractOne(cleaned, phone_directory.keys())

    print(f"Best match: {best_match} (confidence={confidence})")

    if confidence > 60:
        return best_match, phone_directory[best_match]
    else:
        return None, None

# ------------------------------------------
# Main program
# ------------------------------------------
def main():
    spelled = listen_spelled_name()

    if not spelled:
        print("No valid name captured.")
        return

    name, number = lookup_name(spelled)

    if name:
        print(f"\n✅ Name Found: {name}")
        print(f"📞 Phone Number: {number}")
    else:
        print("\n❌ No matching entry found in directory.")

if __name__ == "__main__":
    main()

!pip install pyttsx3
!sudo apt-get install espeak-ng

import speech_recognition as sr
import pyttsx3
from fuzzywuzzy import process

# -----------------------------
# Directory Database
# -----------------------------
phone_directory = {
    "ARIA": "9876543210",
    "JOHN": "9123456789",
    "JESSICA": "9988776655",
    "MICHAEL": "9001122334",
    "SAM": "8745632109"
}

# -----------------------------
# Text-to-Speech engine
# -----------------------------
engine = pyttsx3.init()

def speak(text):
    engine.say(text)
    engine.runAndWait()

# -----------------------------
# Speech-to-Text function
# -----------------------------
def listen():
    r = sr.Recognizer()

    try:
        with sr.Microphone() as source:
            speak("Please spell the name or say the name clearly.")
            print("Listening...")
            audio = r.listen(source)
        text = r.recognize_google(audio)
        print("You said:", text)
        return text.upper()

    except sr.UnknownValueError:
        speak("Sorry, I could not understand.")
    except sr.RequestError:
        speak("Speech service unavailable.")
    except OSError as e:
        if "No Default Input Device Available" in str(e):
            print("\n--- Microphone not found. Please type the name instead. ---")
            text_input = input("Enter the spelled name (e.g., A R I A): ")
            return text_input.upper()
        else:
            print(f"An OSError occurred: {e}")

    return None

# -----------------------------
# Directory lookup
# -----------------------------
def lookup(name):
    cleaned = name.replace(" ", "")
    best_match, score = process.extractOne(cleaned, phone_directory.keys())

    if score > 60:
        return best_match, phone_directory[best_match]
    return None, None

# -----------------------------
# Main program
# -----------------------------
def main():
    spoken = listen()

    if not spoken:
        speak("No input detected.")
        return

    name, number = lookup(spoken)

    if name:
        print(f"Found: {name} -> {number}")
        speak(f"The phone number for {name} is {number}")
    else:
        print("No match found.")
        speak("Sorry, I could not find that name in the directory.")

if __name__ == "__main__":
    main()